### PR TITLE
fix issue JENKINS-72034

### PR DESCRIPTION
**Pull request by ACM-Unit**
There are need to be dependencies to Jaxb for build dimensions api jars with java 11,
so better to add dependencies in dimensionsscm plugin pom instead of adding it as jars to jenkins

### CODE REVIEW

**Review by basil — DISMISSED** [review]
Should rather depend on the `jaxb` library plugin:

https://plugins.jenkins.io/jaxb/dependencies/

**Comment by ACM-Unit** [comment]
@basil thanks for suggestion, also I've noticed that plugin works without any jaxb dependencies in pom with java 11, is it means that Jenkins already include JAXB dependencies as part of its runtime environment and I don't have to add any jaxab dependencies to my pom at all?

**Comment by basil** [comment]
Yes, that sounds right

**Review by PetRay — APPROVED** [review]
Latest changes look good

**Pull request merged**
